spring:
  profiles:
    active:
      - dev

---
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在的目录
  type-aliases-package: com.atguigu.springcloud.entities # 所有Entity别名类所在的包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件



spring:
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouldDB01
    username: root
    password: asddsaasd
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间


server:
  port: 8001

eureka:
  client: # 将服务端注册进eureka服务列表中
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true


info:
  app.name: atguigu-microservicecloud-springcloudconfig2
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$